
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rt-bugFixing","number":61,"title":"Bug and Mutation Fixing","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/61"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"driverAvailabilityControllerpt5","number":57,"title":"Driver Availability: Add controller GET by id endpoint for driver availability","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/57"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"driverAvailabilityControllerpt3","number":56,"title":"Driver Availability: Add controller GET all endpoint for driver availability and tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/56"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-driverAvailabilityPut","number":55,"title":"DriverAvailability:  Added DriverAvailability controller PUT endpoint and tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/55"}]
