
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-admin-app-review-page","number":53,"title":"Admin Rider Application: Review Page","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/53"},{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"cgdriverAvailabilityCreatePage","number":51,"title":"DriverAvailabilityCreate Page and Stories","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjIzNDM4MzQ2","is_bot":false,"login":"calee14","name":"Cappillen Lee"},"headRefName":"cl-rider-app-review-form","number":50,"title":"Admin Rider Application Review Form","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/50"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rt-driverAvailabilityEditPage","number":49,"title":"Added Driver Availability Edit Page and Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-driverAvailabilityIndex","number":38,"title":"DriverAvailability: driverAvailability index page","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/38"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"driverAvailabilityControllerpt2","number":37,"title":"Driver availiability Controller Post method","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/37"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rt-driverAvailabilityForm","number":34,"title":"Driver Availability: Added Driver Availability Form and Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/34"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-driverAvailabilityTable","number":33,"title":"DriverAvailability: Add DriverAvailabilityTable and Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/33"}]
