
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-3
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"driverAvailabilityControllerpt2","number":37,"title":"Driver availiability Controller Post method","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/37"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"driverAvailabilityController","number":36,"title":"Driver availability controller Admin methods and tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjY0MzI4MjM0","is_bot":false,"login":"Rytuose","name":""},"headRefName":"rt-driverAvailabilityForm","number":34,"title":"Added Driver Availability Form and Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/34"},{"author":{"id":"MDQ6VXNlcjQ4Njc4MTQ1","is_bot":false,"login":"wzqd","name":"Jason Gu"},"headRefName":"wzqd-driverAvailabilityTable","number":33,"title":"DriverAvailability: Add DriverAvailabilityTable","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/33"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"josephl-driverAvailability3","number":30,"title":"Josephl driver availability3","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjY4MTY0Njk0","is_bot":false,"login":"cydthe","name":""},"headRefName":"cg-applytoberider","number":28,"title":"Modifying Apply to be a Rider link ","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/28"},{"author":{"id":"MDQ6VXNlcjY5MjgwMTU1","is_bot":false,"login":"JosephLiCodes","name":""},"headRefName":"josephl-driverAvailability","number":27,"title":"feat: add driverAvailability entity and driverAvailabilityFixtures an…","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/pull/27"}]
